version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .

python:
  install:
    - requirements: setup.py

sphinx:
  configuration: docs/source/conf.py
